version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DBUsername}
      POSTGRES_PASSWORD: ${DBPassword}
      POSTGRES_DB: ${DBDatabase}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_service
    env_file:
      - .env
    environment:
      DB_URL: postgresql+asyncpg://${DBUsername}:${DBPassword}@${DBHost}:${DBPort}/${DBDatabase}
    depends_on:
      - db
    ports:
      - "8000:8000"
volumes:
  postgres_data: